name: Deployment

on:
  workflow_run:
    workflows: [ "API Tests" ]
    types: [ completed ]
    branches:
      - main

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to Production
        run: |
          curl -X POST ${{ secrets.DEPLOYMENT_WEBHOOK }}
